/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119166-g1e5c65f539-20250408"
#endif /* AVUTIL_FFVERSION_H */
